#!/bin/sh

# Aliases
command -v dcraw >/dev/null 2>&1 && alias dcraw='dcraw -H 2 -q 3 -o 0'

command -v xrandr >/dev/null 2>&1 && alias vgaon='xrandr --output VGA1 --mode 1024x768 --right-of LVDS1' && alias vgaoff='xrandr --output VGA1 --off'

command -v xclip >/dev/null 2>&1 && alias xpaste='xclip -o | xclip -selection c'

command -v rubber >/dev/null 2>&1 && alias rubber='rubber --pdf'

command -v mp3fs >/dev/null 2>&1 && alias mountmp3='sudo mp3fs ~/Music,320 /mnt/mp3 -o allow_other,ro'

command -v pagsh.openafs >/dev/null 2>&1 && alias adminhat="pagsh.openafs -c 'export KRB5CCNAME=${KRB5CCNAME}_$$; kinit $USER/admin; klist -s && aklog && $SHELL; kdestroy; unlog'"

command -v packer >/dev/null 2>&1 && alias packer='packer --auronly'

systemupdate(){
   DEB="aptitude update || apt-get update; aptitude safe-upgrade || apt-get upgrade;"
   ARCH="pacman -Syu"
   MAC="softwareupdate -ia"
   UPDATE=""
   if [ `uname` = "Linux" ]; then
      ID=`lsb_release -is`
   elif [ `uname` = "Darwin" ]; then
      UPDATE="${MAC}"
   fi
   if [ ${ID} = "Arch" ]; then
      UPDATE="${ARCH}"
   elif [ ${ID} = "Debian" -o ${ID} = "Ubuntu" ]; then
      UPDATE="${DEB}"
   fi
   if [ -n "${UPDATE}" ]; then
      sudo sh -c "${UPDATE}"
   else
      echo "Unsupported system"
   fi
}

# Perl local::lib
export PERL_LOCAL_LIB_ROOT="${HOME}/.perl5";
export PERL_MB_OPT="--install_base ${HOME}/.perl5";
export PERL_MM_OPT="INSTALL_BASE=${HOME}/.perl5";
export PERL5LIB=`perl -MConfig -e 'print "$ENV{HOME}/.perl5/lib/perl5/$Config{archname}:$ENV{HOME}/.perl5/lib/perl5"'`;
concat_path "${HOME}/.perl5/bin"

# vim: set ft=sh ts=3 sw=3 et:
