#!/bin/sh
if [ ! -d .git/info ]; then
    echo "Run at the top of a git repository"
    exit 1
fi
git config core.sparsecheckout true
echo > .git/info/sparse-checkout
for i in "$@"
do
    echo "$i" >> .git/info/sparse-checkout
done
git read-tree -m -u HEAD
